name = "FastAC"
uuid = "67b5c193-ac72-459a-8260-cf84d97d02cd"
version = "0.1.0"
authors = ["Manuel F. Schmid <mfs2173@columbia.edu>"]

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.9.16"
Test = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
